# Generated by Django 4.1.7 on 2023-04-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
