# Generated by Django 4.1.7 on 2023-04-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapp', '0002_alter_tweets_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='search_tag',
            new_name='search_tag_or_username',
        ),
    ]
